platform :ios, '15.0'

source 'https://github.com/forcedotcom/SalesforceMobileSDK-iOS-Specs'
source 'https://github.com/CocoaPods/Specs.git'

def capacitor_pods
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Capacitor', :path => '../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../node_modules/@capacitor/ios'
end

target 'Plugin' do
  pod 'MobileSync', '11.0'
  capacitor_pods
end

target 'PluginTests' do
  capacitor_pods
end
