platform :ios, '15.0'

source 'https://github.com/forcedotcom/SalesforceMobileSDK-iOS-Specs'
source 'https://github.com/CocoaPods/Specs.git'

def capacitor_pods
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Capacitor', :path => '../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../node_modules/@capacitor/ios'
end

target 'Plugin' do
  pod 'MobileSync', '11.0'
  capacitor_pods
end

target 'PluginTests' do
  capacitor_pods
end

post_install do |installer|
  mobile_sdk_post_install(installer)
end

# Post Install: fix deployment targets
def mobile_sdk_post_install(installer)
  installer.pods_project.targets.each do |target|
    # ARC code targeting iOS 8 does not build on Xcode 14.3. Force to at least iOS 9.
    force_to_arc_supported_min = target.deployment_target.to_i < 9
    if force_to_arc_supported_min
      change_deployment_target(target, '9.0')
    end
    
    # Mobile SDK targets
    is_mobile_sdk_target = ['SalesforceAnalytics', 'SalesforceSDKCommon', 'SalesforceSDKCore', 'SmartStore', 'MobileSync', 'SalesforceReact', 'FMDB'].include?(target.name)
    if is_mobile_sdk_target
      change_deployment_target(target, '15.0')
    end
  end
end

def change_deployment_target(target, deployment_target)
  target.build_configurations.each do |config|
    config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = deployment_target
  end
end
